import sys

assert len(sys.argv) > 1

ld_path = sys.argv[1]
names = sys.argv[2:]

overlay = '''/* Warning: autogenerated file - changes will be lost */
SECTIONS {
  . = ORIGIN(ShadowMap);

  OVERLAY 0x0000 : NOCROSSREFS
  {

'''

for name in names:
	overlay += '    .%s_dsp { KEEP(*(.%s*)) }\n' % (name, name)

overlay += '''
  } > ShadowMap

}'''

with open(ld_path, 'w') as fd:
	fd.write(overlay)
