import sys

assert len(sys.argv) > 2

ld_path = sys.argv[1]
platform = sys.argv[2]
names = sys.argv[3:]

assert platform in ('M0', 'M4')

print('Creating script %s for %s' % (ld_path, platform))

overlay = '''/* Warning: autogenerated file - changes will be lost */
SECTIONS {
  . = ORIGIN(ShadowMap);

  OVERLAY 0x0000 : NOCROSSREFS
  {

'''

for name in names:
	if platform == 'M0':
		overlay += '    .%s_dsp { KEEP(*(*instanceInitmydsp));KEEP(*(*buildUserInterfacemydsp)) }\n' % (name)
	else:
		overlay += '    .%s_dsp { KEEP(*(*computemydsp)); }\n' % (name)

overlay += '''
  } > ShadowMap

}'''

with open(ld_path, 'w') as fd:
	fd.write(overlay)
