import sys

assert len(sys.argv) > 2

ld_path = sys.argv[1]
platform = sys.argv[2]
names = sys.argv[3:]

assert platform in ('M0', 'M4')

print('Creating script %s for %s' % (ld_path, platform))

overlay = '''/* Warning: autogenerated file - changes will be lost */
SECTIONS {
  . = ORIGIN(ShadowMap);

  /* All sections are overlayed (cannot co-exist) because:
    * M0 and M4 code sections are loaded into memory and separately shadow-mapped into 0x0000 region
    * M0 init code is loaded, executed and discarded; it doesn't need to co-exist with gui code
    * M4 alloc code is not even loaded, it's only used to extract information on RAM needed for dsp
  */
  OVERLAY 0x0000 : NOCROSSREFS
  {
'''

for name in names:
	if platform == 'M0':
		overlay += '''
    .%s_dsp_M0init { KEEP(*(.%s.text.instanceInitmydsp)) }
    .%s_dsp_M0gui  { KEEP(*(.%s.text.buildUserInterfacemydsp)) }''' % (name, name, name, name)

	else:
		overlay += '''
    .%s_dsp_M4dsp   { KEEP(*(.%s.text.computemydsp)) }
    .%s_dsp_M4alloc { KEEP(*(.%s.text.newmydsp)) }''' % (name, name, name, name)

overlay += '''
  } > ShadowMap

}'''

with open(ld_path, 'w') as fd:
	fd.write(overlay)
